/**
 * Automatic generated by "user.build.js"
 * */
// ==UserScript==
// @name          Pxer-dev
// @version       7
// @namespace     https://github.com/pea3nut/Pxer
// @author        花生PeA
// @description   可能是目前最好用的P站收图工具
// @grant         none
// @noframes
// @include       https://www.pixiv.net*
// @include       http://127.0.0.1/*
// @include       http://localhost/*
// ==/UserScript==
javascript:void((function() {
    // 环境变量
    window['PXER_URL'] =/**/"https://rawgit.com/SetoKaiba/Pxer/dev/";//*/'';
    window['PXER_MODE'] ='dev';

    // 引入入口文件
    document.documentElement.appendChild(
        document.createElement('script')
    ).src=window['PXER_URL']+'jsonp.js?'+(+new Date);

})());
